### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by ThatOneCalculator** [aleksrutins/typst-gtk#1]
Compiled with rust v1.74.1

Crash:

`./target/release/typst-gtk`

```
thread 'main' panicked at src/main.rs:43:10:
Could not load resources: Error { domain: g-file-error-quark, code: 4, message: "Failed to open file “/app/share/typst-gtk/typst-gtk.gresource”: open() failed: No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Backtrace:

`RUST_BACKTRACE=full ./target/release/typst-gtk`

```
thread 'main' panicked at src/main.rs:43:10:
Could not load resources: Error { domain: g-file-error-quark, code: 4, message: "Failed to open file “/app/share/typst-gtk/typst-gtk.gresource”: open() failed: No such file or directory" }
stack backtrace:
   0:     0x55b568ea17ac - std::backtrace_rs::backtrace::libunwind::trace::ha69d38c49f1bf263
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55b568ea17ac - std::backtrace_rs::backtrace::trace_unsynchronized::h93125d0b85fd543c
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55b568ea17ac - std::sys_common::backtrace::_print_fmt::h8d65f438e8343444
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55b568ea17ac - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h41751d2af6c8033a
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55b568ec161c - core::fmt::rt::Argument::fmt::h5db2f552d8a28f63
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/fmt/rt.rs:138:9
   5:     0x55b568ec161c - core::fmt::write::h99465148a27e4883
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/fmt/mod.rs:1114:21
   6:     0x55b568e9f5ce - std::io::Write::write_fmt::hee8dfd57bd179ab2
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/io/mod.rs:1763:15
   7:     0x55b568ea1594 - std::sys_common::backtrace::_print::h019a3cee3e814da4
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55b568ea1594 - std::sys_common::backtrace::print::h55694121c2ddf918
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55b568ea2b13 - std::panicking::default_hook::{{closure}}::h29cbe3da3891b0b0
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:272:22
  10:     0x55b568ea2834 - std::panicking::default_hook::h881e76b2b8c74280
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:292:9
  11:     0x55b568ea3095 - std::panicking::rust_panic_with_hook::hcc36e25b6e33969c
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:731:13
  12:     0x55b568ea2f91 - std::panicking::begin_panic_handler::{{closure}}::ha415efb0f69f41f9
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:609:13
  13:     0x55b568ea1cd6 - std::sys_common::backtrace::__rust_end_short_backtrace::h395fe90f99451e4e
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x55b568ea2ce2 - rust_begin_unwind
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
  15:     0x55b568e7a535 - core::panicking::panic_fmt::h452a83e54ecd764e
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
  16:     0x55b568e7a993 - core::result::unwrap_failed::hed0fccbe07e724fc
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/result.rs:1652:5
  17:     0x55b568e809b6 - typst_gtk::main::h0491cda1fdc457b0
  18:     0x55b568e7ff33 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5dfce5b0cd9994c5
  19:     0x55b568e7f5c9 - std::rt::lang_start::{{closure}}::hdb698bf416ad99fb
  20:     0x55b568e9cf2b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h14c5f6d1cd70a60f
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:284:13
  21:     0x55b568e9cf2b - std::panicking::try::do_call::h2d02374ca451446a
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:504:40
  22:     0x55b568e9cf2b - std::panicking::try::h9f7922394bf57392
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:468:19
  23:     0x55b568e9cf2b - std::panic::catch_unwind::ha1600f9dd4ee7270
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panic.rs:142:14
  24:     0x55b568e9cf2b - std::rt::lang_start_internal::{{closure}}::hfbd80e7d681b21a1
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/rt.rs:148:48
  25:     0x55b568e9cf2b - std::panicking::try::do_call::heacaa33dbdaa16e0
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:504:40
  26:     0x55b568e9cf2b - std::panicking::try::h637875f7c9db85ea
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:468:19
  27:     0x55b568e9cf2b - std::panic::catch_unwind::h4caa9c0c78cb4c19
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panic.rs:142:14
  28:     0x55b568e9cf2b - std::rt::lang_start_internal::h2d6a60ec944b523d
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/rt.rs:148:20
  29:     0x55b568e80ab5 - main
  30:     0x7fd00753fcd0 - <unknown>
  31:     0x7fd00753fd8a - __libc_start_main
  32:     0x55b568e7ac55 - _start
  33:                0x0 - <unknown>
```

**Comment by ThatOneCalculator** [comment]
Changing these two lines to be `/usr/share` instead of `/app/share`:

https://github.com/aleksrutins/typst-gtk/blob/84e7a90ce6d839a0b90fb4e1706bff237d680e62/src/config.rs#L3-L4

And then placing the contents of https://github.com/aleksrutins/typst-gtk/blob/master/data/com.rutins.Typst.gschema.xml in `/usr/share/typst-gtk/typst-gtk.gresource`

Yields this new error:

`./target/release/typst-gtk`

```
thread 'main' panicked at src/main.rs:43:10:
Could not load resources: Error { domain: g-resource-error-quark, code: 1, message: "/usr/share/typst-gtk/typst-gtk.gresource: invalid gvdb header" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
